" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

filetype off        " required by Vundle. We will enable it afterwards

" Set the runtime path to include Vundle and initialize
" set rtp+=$HOME/.config/vim/bundle
" set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=$HOME/.homesick/repos/Vundle.vim
set rtp+=/usr/share/vim/vimfiles/autoload/vundle.vim

" call vundle#begin()
" Alternatively, pass a path where Vundle should install plugins
call vundle#begin("$HOME/.local/share/vim/bundle")

" Let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" List of plugins/Vundles
Plugin 'https://github.com/blueshirts/darcula.git'  " One of my favourites color scheme
Plugin 'hzchirs/vim-material'                       " One of my favourites color scheme
Plugin 'mhinz/vim-startify'                         " Startup screen
Plugin 'vim-airline/vim-airline'                    " Vim status bar
Plugin 'edkolev/tmuxline.vim'                       " Tmux status bar
Plugin 'ptzz/lf.vim'                                " Integrates lf in vim
" Plugin 'junegunn/fzf'                               " Integrates fzf in vim
Plugin 'junegunn/fzf.vim'                           " Integrates fzf in vim
Plugin 'mattn/webapi-vim'                           " Dependency plugin for gists
Plugin 'mattn/gist-vim'                             " Github gists
Plugin 'airblade/vim-gitgutter'                     " Show git differences in gutter
Plugin 'kshenoy/vim-signature'                      " Show Marks in gutter
Plugin 'ZoomWin'                                    " Maximize/Restore Window
Plugin 'qpkorr/vim-bufkill'                         " Close all buffers except the active one
Plugin 'tpope/vim-commentary'                       " Collapse/Expand comments
Plugin 'mtth/scratch.vim'                           " Show/Hide Scratch files for quickly writting ideas/notes
Plugin 'vimwiki/vimwiki'                            " Wiki
Plugin 'junegunn/goyo.vim'                          " Distraction free writting plugin
Plugin 'farseer90718/vim-taskwarrior'               " Vim interface for taskwarrior
"Plugin 'nelstrom/vim-markdown-folding'
Plugin 'godlygeek/tabular'                          " Dependency plugin for vim-markdown
Plugin 'plasticboy/vim-markdown'                    " Markdown goodies (folding, styles - concealing etc)
Plugin 'echuraev/translate-shell.vim'               " Translate without leaving Vim
Plugin 'tbabej/taskwiki'                            " Interact with Taskwarrior from Vimwiki
Plugin 'mattn/calendar-vim'                         " Add a calendar to Vim (Optionally used by taskwiki)

" All of your Plugins must be added before the following line
call vundle#end()

" Function to source only if file exists {
function! SourceIfExists(file)
  if filereadable(expand(a:file))
    exe 'source' a:file
  endif
endfunction
" }

filetype plugin indent on

syntax on                   " Enable syntax highlighting
set guifont=Inconsolata\ for\ Powerline:h15
set number
set relativenumber

" let g:material_style='palenight' " palenight/oceanic variants
silent! colorscheme vim-material " Load colorschema but don't complaint if it doesn't exists

" if has("gui_running")
    set background=dark
    " Make the background transparent
    highlight Normal guibg=NONE ctermbg=NONE 
" endif

" Make backspace behave like in the rest of the applications
"   https://vi.stackexchange.com/a/2163
set backspace=indent,eol,start

" Status line
set showcmd         " Show partial/incomplete commands in the last line of the screen
set showmode        " Let yorself know in which mode you are in
set wildmenu        " Display completion matches in a status line
set laststatus=2    " Always display the status line, even if only one window is displayed

" Line behaviours
set wrap            " Wrap lines visually. Long lines will be displayed as multiple lines
set textwidth=0     " Prevent automatic wrap of lines
set wrapmargin=0    " Prevent automatic wrap of lines (right margin)

" Prefer spaces over tabs
set expandtab       " Insert spaces when the tab key is pressed
set tabstop=4       " Set the number of spaces to be added (after expandtab is set)
set shiftwidth=4    " Change the number of space characters inserted for indentation
set softtabstop=4   " Makes the backspace key threat the four spaces like a tab (one backspace goes back a full 4 spaces)
set autoindent      " Copy the indentation from the previous line

" Buffers
set hidden          " Allow switching buffers with unsaved changes
set confirm         " Ask for confirmation before quitting when there are buffers with unsaved changes

" Splits
set splitbelow      " Open new vertical splits below
set splitright      " Open new horizontal splits on the right

" Search
set ignorecase      " Use case insensitive search
set smartcase       " Except when using capital letters
set hlsearch        " Highlight searches

" Centralise swap and undo files
set directory=$HOME/.cache/vim/swap/
set undodir=~/.cache/vim/undo/
set undofile
set viewdir=$HOME/.cache/vim/view/

" Enable mouse - I know, but it is useful for long reads while snacking :)
set mouse=a

" Jump to last position when opening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

" Auto enable Goyo for Markdown and Vimwiki files
augroup wants_goyo
    autocmd!
    autocmd Filetype,BufEnter markdown,mkd,vimwiki call s:auto_goyo()
augroup END

function! s:auto_goyo()
    if exists('#goyo')
      let bufnr = bufnr('%')
      Goyo!
      execute 'b '.bufnr
    else
      Goyo 80
  endif
endfunction

setlocal spell spelllang=en_us
set complete+=kspell
autocmd BufRead,BufNewFile *.md setlocal spell

" Filetype settings
filetype on
filetype plugin on  " Enable file type detection
filetype indent on  " Detects indentation based on indentation scripts located in the indent folder of the vim installation

" Key mappings {{{
let mapleader=" "

vmap <up> <NOP>
vmap <down> <NOP>
vmap <left> <NOP>
vmap <right> <NOP>

noremap <up> <NOP>
noremap <down> <NOP>
noremap <left> <NOP>
noremap <right> <NOP>

"inoremap <up> <NOP>
"inoremap <down> <NOP>
"inoremap <left> <NOP>
"inoremap <right> <NOP>

" Remap ESC
inoremap jj <ESC>
inoremap jk <ESC>

" Move around (get the codes by typing CTRL + V and CTRL + desired key in insert mode)
noremap [B ddp                                " Move lines down
noremap [A ddkP                               " Move lines up

" Splits 
nnoremap <c-j> <c-w><c-j>                       " Move to the split below
nnoremap <c-k> <c-w><c-k>                       " Move to the split above
nnoremap <c-l> <c-w><c-l>                       " Move to the split at the right
nnoremap <c-h> <c-w><c-h>                       " Move to the split at the left

" nnoremap <c-w>M <C-W>\| <C-W>_                  " Maximize the window
" nnoremap <c-w>m <C-W>=                          " Resize window (50%)

" Clipboard
vmap YY "+y<CR>
" noremap YY "*y<CR>
noremap YY "*y<CR>
noremap PP "*gP<CR>
noremap XX "*x<CR>

nmap <silent> <leader>ev :e $HOME/.vimrc<cr>    " Edit this file ('e'dit 'v'imrc)
" nmap <silent> <leader>sv :so $HOME/.vimrc<cr>   " Source this file ('s'ource 'v'imrc)
nmap <silent> <leader>sv :so $MYVIMRC<cr>   " Source this file ('s'ource 'v'imrc)

nnoremap <leader>q :b # <bar> :bd! # <CR>       " Close buffer without closing Goyo

nnoremap <leader>r :nohl<CR><C-L>               " Map Redraw screen (<leader>r) to also turn off search highlighting

noremap <Leader>W :w !sudo tee % > /dev/null    " Save as sudo

" map <leader>f :Lf<CR>.
map <leader>f :FZF<CR>
map <leader>b :Buffers<CR>
map <silent> <c-s> :Startify<CR>                " Open Startify
map <silent> <c-n> :NERDTreeToggle<CR>          " Open NERDTree

" Plugings Settings {{{
" =====================
" = Plugings Settings =
" =====================
" Load fzf
set rtp+=$HOMEBREW_PREFIX/bin/fzf
" set rtp+=/usr/local/opt/fzf

" Startify
let g:startify_bookmarks = [ {'v': '~/.vimrc'} , {'z': '~/.zshrc'} ]
let g:startify_list_order = [
        \ ['   Bookmarks:'], 'bookmarks',
        \ ['   Recently used files:'], 'files',
        \ ['   Recently used in current directory:'], 'dir',
        \ ['   Sessions:'], 'sessions',
        \ ['   Command:'], 'commands',
    \ ]

" NERDTree
" let g:NERDTreeDirArrowExpandable="▸"
" let g:NERDTreeDirArrowCollapsible="▾"

" Gist
let g:gist_show_privates = 1
let g:gist_post_private = 1
let g:gist_detect_filetype = 1

" Gitgutter
let g:gitgutter_enabled = 1
let g:gitgutter_signs = 1
let g:gitgutter_highlight_lines = 0

" Tmuxline
let g:airline#extensions#tmuxline#enabled = 0 " Let vim-airline manage the colors

" Vim Wiki
let wiki_default = {}
let wiki_default.auto_export = 1 " Won't work since at the moment only works for default syntax and not for markdown
let wiki_default.auto_toc = 1
let wiki_default.index = 'index'
let wiki_default.syntax = 'markdown'
let wiki_default.ext = '.md'
let wiki_default.nested_syntaxes = {'php': 'php', 'bash': 'sh', 'py': 'python', 'js': 'javascript', 'html': 'html', 'css': 'css'}

let personal_wiki = copy(wiki_default)
let personal_wiki.path = '~/Dropbox/Documents/Wikis/Personal/'
let personal_wiki.html_path = '~/Dropbox/Documents/Public/Wikis/Personal/Export/'

let work_wiki = copy(wiki_default)
let work_wiki.path = '~/Dropbox/Documents/Wikis/Westwing/'
let work_wiki.html_path = '~/Dropbox/Documents/Public/Wikis/Westwing/Export/'

let g:vimwiki_list = [work_wiki, personal_wiki]

let g:vimwiki_hl_headers = 1 " Colors for headers
let g_vimwiki_hl_cb_checked = 1
let g:vimwiki_global_ext = 0
let g:vimwiki_menu = ''
let g:vimwiki_listsyms = '✗○◐●✓'
let g:vimwiki_folding= 'custom'

" Scratch.vim
let g:scratch_persistence_file = '~/.scratch.md'

" vimpager
if exists('g:vimpager')
"  colorscheme desert
endif

let g:vimpager = {}
let g:less     = {}

let g:vimpager.ansiesc = 0
let g:vimpager.passthrough = 1

" DbExt
let g:dbext_default_passwd_use_secret = 1
let g:dbext_default_prompt_for_variables = 0
let g:dbext_default_stop_prompt_for_variables = 2
let g:dbext_default_display_cmd_line = 0 
let g:dbext_default_variable_remember = 1

call SourceIfExists("~/.vim/dbextrc")

" Lf
let g:lf_map_keys = 0
let g:lf_replace_netrw = 1 
" let g:lf_command_override = 'lf --cmd "set show_hidden=true"'
" map <leader>f :Lf<CR>.

" FZF

" Vim Taskwarrior
let g:task_rc_override = 'rc.defaultwidth=0'

" Taskwiki
let g:taskwiki_taskrc_location = '~/.config/taskwarrior/taskrc'
let g:taskwiki_data_location = '~/.local/share/taskwarrior'
let g:taskwiki_source_tw_colors = 'yes'
