#!/bin/bash

# Main aliases
alias ls='ls --color=auto'
alias ll='ls -lahtr'
alias mv='mv -iv'
alias cp='cp -riv'
alias mkdir='mkdir -vp'
alias rm='rmtrash -vI'
alias ..='cd ..'
alias ...='cd ../../'
alias cd..='cd ..'
alias :q=' exit'
alias :Q=' exit'
alias :x=' exit'
alias less="${PAGER}"
alias mless="${MANPAGER}"
alias grep='grep --color=auto'
alias prettyjson='python -m json.tool'

# @TODO make it work for bash and zsh
alias dotfiles-reload="source ${HOME}/.zshrc"
alias dotfiles-edit="${EDITOR} ${HOME}/.zshrc"

# Bookmarks
# @TODO Find alternative for bookmarks
alias cddesk="cd ${HOME}/Desktop"
alias cddown="cd ${HOME}/Downloads"
alias cddocs="cd ${HOME}/Documents"
alias cddev="cd ${HOME}/Development"
alias cdtmp="cd ${HOME}/tmp"
alias cddrop="cd ${HOME}/Dropbox"
alias cdmovies="cd ${HOME}/Movies"
alias cdmusic="cd ${HOME}/Music"
alias cdwwdocs="cd ${HOME}/Documents/Westwing"
alias cdwwdev="cd ${HOME}/Development/Westwing"


# Sshuttle
alias sshuttle="sshuttle -D --pidfile /var/run/sshuttle.pid -v "
alias sshuttle-stop='kill $(cat /var/run/sshuttle.pid)'
alias sshuttle-log="sudo tail -f /var/log/system.log | grep --line-buffered sshuttle"
alias sshuttle-westwing="sshuttle --dns -r ssh.westwing.eu 0/0"

# Docker
alias dcs="docker-compose $*"
alias ddv="docker volume ls -q -f 'dangling=true'"
alias ddi="docker images -f 'dangling=true' -q"
alias drun="docker run -it --rm $*"

if [[ "${OSTYPE}" == "linux-gnu" ]]; then
    _source_file "${XDG_CONFIG_HOME}/shell/alias/linux"
elif [[ "${OSTYPE}" == "darwin" ]]; then
    _source_file "${XDG_CONFIG_HOME}/shell/alias/darwin"
fi

